#ifndef DEFINITION_DRIVER_DMA_H__
#define DEFINITION_DRIVER_DMA_H__

#include <hw.h> //ok

// DMA0: RX (nRF → Cortex-M3) 설정
#define DRIVER_DMA0_CFG0   (DMA_LITTLE_ENDIAN | DEST_TRANS_LENGTH_SEL | DMA_PRIORITY_1 | DMA_SRC_SPI1 | DMA_DEST_ALWAYS_ON | WORD_SIZE_32BITS_TO_32BITS | DMA_SRC_ADDR_STATIC \
                            | DMA_DEST_ADDR_INCR_1 | DMA_SRC_ADDR_LSB_TOGGLE_DISABLE | DMA_DEST_ADDR_LSB_TOGGLE_DISABLE | DMA_CNT_INT_DISABLE | DMA_COMPLETE_INT_ENABLE)
#define DRIVER_DMA0_CTRL   (DMA_DISABLE | DMA_CLEAR_CNTS | DMA_CLEAR_BUFFER | DMA_KEEP_BUFFER_WHEN_WRAPPING | DMA_INT_CNT_ADDR_WRAP_DISABLE | DMA_TRIGGER_CH0_COMPLETED | DMA_INT_CNT_TRIGGER_DISABLE)
#define DRIVER_DMA0_STATUS (DMA_COMPLETE_INT_CLEAR | DMA_CNT_INT_CLEAR)

// DMA1: RX (Cortex-M3 → nRF) 설정
#define DRIVER_DMA1_CFG0  (DMA_LITTLE_ENDIAN | SRC_TRANS_LENGTH_SEL | DMA_PRIORITY_1 | DMA_SRC_ALWAYS_ON | DMA_DEST_SPI1 | WORD_SIZE_32BITS_TO_32BITS | DMA_SRC_ADDR_INCR_1 \
                            | DMA_DEST_ADDR_STATIC | DMA_SRC_ADDR_LSB_TOGGLE_DISABLE | DMA_DEST_ADDR_LSB_TOGGLE_DISABLE | DMA_CNT_INT_DISABLE | DMA_COMPLETE_INT_ENABLE)
#define DRIVER_DMA1_CTRL   (DMA_DISABLE | DMA_CLEAR_CNTS | DMA_CLEAR_BUFFER | DMA_KEEP_BUFFER_WHEN_WRAPPING | DMA_INT_CNT_ADDR_WRAP_DISABLE | DMA_TRIGGER_CH0_COMPLETED | DMA_INT_CNT_TRIGGER_DISABLE)
#define DRIVER_DMA1_STATUS (DMA_COMPLETE_INT_CLEAR | DMA_CNT_INT_CLEAR)

#endif
