#ifndef __tdc_hal_dma_h__
#define __tdc_hal_dma_h__

#include <hw.h> //ok

/* 워드 크기 8비트 전환 (2026-07-27)
 * SPI1 은 이미 SPI_WORD_SIZE_8 로 동작하는데 DMA 만 32비트로 퍼 담고 있어서
 * 패킷 버퍼가 int[21] (84바이트) 이 되어 있었다. 8BITS_TO_8BITS 로 바꾸면
 * uint8_t[21] (21바이트) 로 1:1 대응된다.
 *
 * transferLength(21) 와 ADDR_INCR_1 은 바꾸지 않는다.
 *   - transferLength 는 "워드 개수" 다. 워드가 8비트로 줄어도 21개 그대로다.
 *   - ADDR_INCR_1 은 "워드 크기 1개 분" 증가이므로 4바이트에서 1바이트로 자동 축소된다.
 *
 * DMA_LITTLE_ENDIAN(=BYTE_ORDER 0) 유지 필수. 하드웨어 레퍼런스 §19.4.2.6 의
 * "8비트 동일 워드 크기에서 니블 재배치" 는 byte ordering 이 켜진 경우
 * (DMA_BIG_ENDIAN=1) 에만 적용되므로 현 설정에서는 발동하지 않는다. */

// DMA0: RX (nRF → Cortex-M3) 설정
#define TDC_HAL_DMA0_CFG0   (DMA_LITTLE_ENDIAN | DEST_TRANS_LENGTH_SEL | DMA_PRIORITY_1 | DMA_SRC_SPI1 | DMA_DEST_ALWAYS_ON | WORD_SIZE_8BITS_TO_8BITS | DMA_SRC_ADDR_STATIC \
                            | DMA_DEST_ADDR_INCR_1 | DMA_SRC_ADDR_LSB_TOGGLE_DISABLE | DMA_DEST_ADDR_LSB_TOGGLE_DISABLE | DMA_CNT_INT_DISABLE | DMA_COMPLETE_INT_ENABLE)
#define TDC_HAL_DMA0_CTRL   (DMA_DISABLE | DMA_CLEAR_CNTS | DMA_CLEAR_BUFFER | DMA_KEEP_BUFFER_WHEN_WRAPPING | DMA_INT_CNT_ADDR_WRAP_DISABLE | DMA_TRIGGER_CH0_COMPLETED | DMA_INT_CNT_TRIGGER_DISABLE)
#define TDC_HAL_DMA0_STATUS (DMA_COMPLETE_INT_CLEAR | DMA_CNT_INT_CLEAR)

// DMA1: RX (Cortex-M3 → nRF) 설정
#define TDC_HAL_DMA1_CFG0  (DMA_LITTLE_ENDIAN | SRC_TRANS_LENGTH_SEL | DMA_PRIORITY_1 | DMA_SRC_ALWAYS_ON | DMA_DEST_SPI1 | WORD_SIZE_8BITS_TO_8BITS | DMA_SRC_ADDR_INCR_1 \
                            | DMA_DEST_ADDR_STATIC | DMA_SRC_ADDR_LSB_TOGGLE_DISABLE | DMA_DEST_ADDR_LSB_TOGGLE_DISABLE | DMA_CNT_INT_DISABLE | DMA_COMPLETE_INT_ENABLE)
#define TDC_HAL_DMA1_CTRL   (DMA_DISABLE | DMA_CLEAR_CNTS | DMA_CLEAR_BUFFER | DMA_KEEP_BUFFER_WHEN_WRAPPING | DMA_INT_CNT_ADDR_WRAP_DISABLE | DMA_TRIGGER_CH0_COMPLETED | DMA_INT_CNT_TRIGGER_DISABLE)
#define TDC_HAL_DMA1_STATUS (DMA_COMPLETE_INT_CLEAR | DMA_CNT_INT_CLEAR)

#endif
